In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('all.csv', header=0)

In [3]:
df.head()

,username,date,text,tags,translated_text,sentiment,location,lat,long,sentiment_label,KADAA_ID,KADAA_AR,KADAA_EN,MOHAFAZA_ID,MOHAFAZA_AR,MOHAFAZA_EN
0,Lebanon 24,2020-07-12,"#كورونا يتلف رئة ""أبو عزرائيل"" (صورة) #العراق#...",#كورونا;#العراق;#lebanon24,"Corona damages the lung of ""Abu Azrael"" (photo...",0.000000,صور,33.2733,35.1939,Neutral,83000,صور,Sour,8,الجنوب,South
1,Sana,2020-07-12,حضرة اساتذة القانون بالجامعة اللبنانية المحترم...,#كورونا;#امتحانات_الموت,Honorable professors of law at the Lebanese Un...,0.325000,العربانية,33.8772,35.6786,Positive,51000,بعبدا,Baabda,5,جبل لبنان,Mount Lebanon
2,Jaras Scoop FM,2020-07-12,"كشفت ""رابطة طلاب الجامعة اللبنانية"" عبر تويتر ...",#كورونا,"The ""Lebanese University Students Association""...",-0.300000,طلصا,33.4833,35.3471,Negative,81000,صيدا,Saida,8,الجنوب,South
3,Lebanon Debate,2020-07-12,"حالة ""#كورونا"" جديدة في الجامعة اللبنانية - ال...",#كورونا,"New ""# Corona"" case at the Lebanese University...",0.136364,حاقل,34.1705,35.7501,Positive,56000,جبيل,Jbeil,5,جبل لبنان,Mount Lebanon
4,عاجل - قناة فلسطين اليوم,2020-07-12,#عاجلمدير مكتب إعلام الأسرى ناهد الفاخوري: حذر...,#كورونا;#عاجل,#UrgentThe director of the Prisoners' Informat...,-0.283333,مكاتبة,33.5628,35.3789,Negative,81000,صيدا,Saida,8,الجنوب,South

In [11]:
df[['year', 'month', 'day']] = df.date.str.split('-', expand=True)

In [37]:
kadaas = df.groupby(['year', 'month', 'KADAA_ID'])
len(kadaas.groups)

206

In [38]:
count_col = []
for n, g in kadaas:
    if n[1] != '01':
        count_col.append(len(g))
count_col = pd.Series(count_col)
count_col

0      210
1       26
2      138
3      893
4       64
      ...
175      9
176      1
177      1
178      2
179      6
Length: 180, dtype: int64

In [39]:
count_col.sum()

45071

In [53]:
df2 = pd.read_csv('kadaas_over_time.csv', header=0)

In [54]:
len(df2)

182

In [55]:
g = df2.groupby('KADAA_ID')
for n1, g1 in g:
    print(g1.month.unique())

[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]

In [60]:
# Solves the Kaddas problem where 42000, 77000 Kadaas of month 8 doesn't have any tweet
# df2['tweets_nb'] = -1
# j = 0
# for i in range(len(df2)):
#     if df2.loc[i, 'month'] == 8 and (df2.loc[i, 'KADAA_ID'] == 77000 or df2.loc[i, 'KADAA_ID'] == 42000):
#         df2.loc[i, 'tweets_nb'] = 1
#     else:
#         df2.loc[i, 'tweets_nb'] = count_col[j]
#         j += 1

In [31]:
df2['tweets_nb'] = count_col

In [61]:
df2

,year,month,KADAA_ID,KADAA_AR,KADAA_EN,topics,sentiment,sentiment_label,tweets_nb
0,2020,2,11000,عكّار,Akkar,"['Therapy', '#jobs']",0.111493,Positive,210
1,2020,2,21000,الهرمل,El Hermel,"['#الكورونا', 'تعليق الطائرات القادمة', '#وزير...",0.018459,Positive,26
2,2020,2,22000,بعلبك,Baalbek,"['Medical Aid', 'healthcare services']",0.045994,Positive,138
3,2020,2,31000,بيروت,Beirut,"['#كورونا #لبنان', 'refugees', 'وزير الصحة', '...",0.061562,Positive,893
4,2020,2,41000,زحلة,Zahle,"['#كورونا #لبنان_ينتفض #لا_داعي_للهلع', 'first...",0.053406,Positive,64
...,...,...,...,...,...,...,...,...,...
177,2020,8,76000,بشرّي,Bcharre,"['#Covid_19 #ChinaVirus', 'coronavirus pandemic']",-0.800000,Negative,1
178,2020,8,77000,المنية-الضنّية,El Minieh-Dennieh,"['لبنان', 'كورونا']",0.040890,Positive,1
179,2020,8,81000,صيدا,Saida,"['فيروس كورونا', 'منظمة الصحة العالمية']",0.000000,Neutral,1
180,2020,8,82000,جزّين,Jezzine,['#ما_تستهتر #كورونا_فايروس'],0.300000,Positive,2
181,2020,8,83000,صور,Sour,"['#كورونا_لبنان', 'شعب بلا مخ', '#شعب_مخدر', '...",-0.018333,Negative,6

In [64]:
df2.to_csv('kadaas_over_time_v2.csv', index=False)

In [62]:
df2[df2.month == 8]

,year,month,KADAA_ID,KADAA_AR,KADAA_EN,topics,sentiment,sentiment_label,tweets_nb
156,2020,8,11000,عكّار,Akkar,"['#كورونا_لبنان', 'ايقاف زفاف فاليري أبو شقرا'...",0.061237,Positive,10
157,2020,8,21000,الهرمل,El Hermel,"['#COVID19 #Lebanon', 'infections', '#wear_you...",0.073333,Positive,6
158,2020,8,22000,بعلبك,Baalbek,"['#كورونا_لبنان_سبسيال', '#سكروا_البلد_وازربوا...",0.034091,Positive,4
159,2020,8,31000,بيروت,Beirut,"['#كورونا #لبنان', 'فيروس كورونا', 'اصابة جديد...",0.088088,Positive,44
160,2020,8,41000,زحلة,Zahle,"['فيروس كورونا', '#لبنان_يحتضر', '#Lebanon', '...",-0.044822,Negative,6
161,2020,8,42000,البقاع الغربي,West Bekaa,"['#لبنان', '#كورونا']",0.066807,Positive,1
162,2020,8,43000,راشيّا,Rachaya,"['كورونا', 'انتشار الفايروس', 'حمد حسن']",0.066071,Positive,1
163,2020,8,51000,بعبدا,Baabda,"['#كورونا #لبنان', 'فيروس كورونا', 'حالة وفاة ...",-0.000706,Negative,11
164,2020,8,52000,المتن,El Meten,"['الدرك ينفذ القانون', '#Covid_19 #كورونا', 'و...",-0.034731,Negative,9
165,2020,8,53000,الشّوف,Ech Chouf,['#كورونا'],0.000000,Neutral,1
166,2020,8,54000,عاليه,Aley,"['كورونا', 'حالات وفاة', '#لبنان', 'إصابة جديد...",0.034091,Positive,4
167,2020,8,55000,كسروان,Kesserouane,"['#Covid_19', '#كورونا_لبنان', 'التباعد الاجتم...",-0.000783,Negative,11
168,2020,8,56000,جبيل,Jbeil,"['كورونا', 'إصابة جديدة', 'لبنان', '#كورونا', ...",0.063024,Positive,13
169,2020,8,61000,النبطيّة,El Nabatieh,"['#عيب_عليك تستخف', 'بأرواح الناس', 'كورونا مش...",-0.088542,Negative,3
170,2020,8,62000,بنت جبيل,Bent Jbeil,"['#Covid_19 #foodsecurity', '#كورونا', '#لبنان...",-0.018939,Negative,3
171,2020,8,63000,مرجعيون,Marjaayoun,"['لبنان', 'يجب إعادة إغلاق المطار', 'فيروس كور...",0.000000,Neutral,1
172,2020,8,64000,حاصبيّا,Hasbaya,"['الإحتفال بسقوط الهيكل', '#كرمالك_يا_وطن #ان_...",0.100000,Positive,1
173,2020,8,71000,طرابلس,Tripoli,"['#كورونا_لبنان', 'طرابلس مليانة #كورونا', 'ال...",0.055556,Positive,3
174,2020,8,72000,الكورة,El Koura,"['#Covid_19', 'استهتار عند الأهل', '#لبنان_يحت...",-0.000946,Negative,19
175,2020,8,73000,زغرتا,Zgharta,['#كورونا #كورونا_لبنان'],-0.009747,Negative,8
176,2020,8,74000,البترون,El Batroun,"['منظمة الصحة العالمية', 'ما لازم نستهتر', 'جا...",0.071021,Positive,9
177,2020,8,76000,بشرّي,Bcharre,"['#Covid_19 #ChinaVirus', 'coronavirus pandemic']",-0.800000,Negative,1
178,2020,8,77000,المنية-الضنّية,El Minieh-Dennieh,"['لبنان', 'كورونا']",0.040890,Positive,1
179,2020,8,81000,صيدا,Saida,"['فيروس كورونا', 'منظمة الصحة العالمية']",0.000000,Neutral,1
180,2020,8,82000,جزّين,Jezzine,['#ما_تستهتر #كورونا_فايروس'],0.300000,Positive,2
181,2020,8,83000,صور,Sour,"['#كورونا_لبنان', 'شعب بلا مخ', '#شعب_مخدر', '...",-0.018333,Negative,6