# Imports

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Hotspot Words & Stop Words

In [2]:
with open('words.txt', 'r', encoding='utf-8') as f:
    hotspot_words = f.read().split('\n')

In [3]:
stopwords = []

with open('../stop-words/arabic.txt', 'r', encoding='utf-8') as f:
    stopwords += f.read().split('\n')

with open('../stop-words/english.txt', 'r', encoding='utf-8') as f:
    stopwords += f.read().split('\n')

stopwords += ['com', 'd9', 'd8', 'شو', 'أن', 'مش', 'يا', 'http', 'إلى', 'عم', 'pic', 'twitter', 'الله', 'بس', 'ly', 'شي' , 'انو',
              'انو', 'رح', 'bit', 'يلي', 'https', 'اللي', 'صباح_الخير', 'saudi24_tv', 'ليرتفع', 'corona', 'covid', 'covid19', 
             'كورونا', 'لبنان', 'وزارة', 'وزير', 'العالمية', 'will']    

# stopwords

# Functions

In [4]:
def tf_idf(data, stopwords=None, start=0, end=3000, ngram=(1, 1)):
    tf_Idf = TfidfVectorizer(stop_words=stopwords, ngram_range=ngram)
    tf_Idf_fit = tf_Idf.fit_transform(data.loc[start:end])
    feature_names = tf_Idf.get_feature_names()
        
    dense = tf_Idf_fit.todense()
    denselist = dense.tolist()

    tf_idf_table = pd.DataFrame(denselist, columns=feature_names)

    tf_idf_result = pd.DataFrame()
    tf_idf_result[['topic', 'score']] = tf_idf_table.mean().reset_index()
    tf_idf_result = tf_idf_result.sort_values('score', ascending=False).reset_index(drop=True)
    
    return tf_idf_result


def get_data(keyword):
    mask = df.translated_text.str.lower().str.contains(keyword.lower())
    data = df[mask].translated_text
    return tf_idf(data, stopwords=stopwords, ngram=(2, 3))

def print_series(s, limit=-1):
    for x in s[:limit]:
        print(x)

# Data

In [5]:
df = pd.read_csv('all.csv', header=0)

# Tests

In [6]:
get_data('university').loc[:20]

d:\desktop\github\m2-project\twittervenv\lib\site-packages\sklearn\feature_extraction\text.py:386: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['aren', 'can', 'couldn', 'didn', 'doesn', 'don', 'hadn', 'hasn', 'haven', 'isn', 'let', 'll', 'mustn', 're', 'shan', 'shouldn', 've', 'wasn', 'weren', 'won', 'wouldn'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

                                 topic     score
0                  lebanese university  0.048556
1                  faculty information  0.018022
2         lebanese university students  0.016901
3                  university students  0.016901
4                          death exams  0.015531
5   lebanese university corona_lebanon  0.015223
6            university corona_lebanon  0.015223
7                         rafic hariri  0.014414
8                  university hospital  0.014347
9                    university death_  0.012254
10          lebanese university death_  0.012254
11     information lebanese university  0.011651
12                information lebanese  0.011651
13        faculty information lebanese  0.011651
14             rafic hariri university  0.010600
15          hariri university hospital  0.010600
16                   hariri university  0.010600
17                 american university  0.010362
18                 death_ examinations  0.010155
19      university death_ examinations  0.010155
20         student lebanese university  0.009584

In [7]:
get_data('prison').loc[:20]

d:\desktop\github\m2-project\twittervenv\lib\site-packages\sklearn\feature_extraction\text.py:386: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['aren', 'can', 'couldn', 'didn', 'doesn', 'don', 'hadn', 'hasn', 'haven', 'isn', 'let', 'll', 'mustn', 're', 'shan', 'shouldn', 've', 'wasn', 'weren', 'won', 'wouldn'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

                           topic     score
0                general amnesty  0.032338
1          arrival virus prisons  0.030043
2                    al fakhouri  0.030043
3             virus prisons data  0.030043
4                  virus prisons  0.030043
5             information office  0.030043
6                 warned arrival  0.030043
7           warned arrival virus  0.030043
8      previously warned arrival  0.030043
9              previously warned  0.030043
10        al fakhouri previously  0.030043
11                    much worse  0.030043
12           fakhouri previously  0.030043
13    fakhouri previously warned  0.030043
14                 arrival virus  0.030043
15                  prisons data  0.030043
16            urgentthe director  0.025222
17  prisoners information office  0.025222
18             nahid al fakhouri  0.025222
19        foreshadows much worse  0.025222
20              foreshadows much  0.025222

In [8]:
get_data('shop').loc[:20]

d:\desktop\github\m2-project\twittervenv\lib\site-packages\sklearn\feature_extraction\text.py:386: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['aren', 'can', 'couldn', 'didn', 'doesn', 'don', 'hadn', 'hasn', 'haven', 'isn', 'let', 'll', 'mustn', 're', 'shan', 'shouldn', 've', 'wasn', 'weren', 'won', 'wouldn'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

                           topic     score
0                sharing thewall  0.026038
1               beirut just want  0.025198
2                    shop beirut  0.025198
3               shop beirut just  0.025198
4                      just want  0.025198
5                 just want know  0.025198
6                    beirut just  0.025198
7                      want know  0.025198
8                     truth news  0.022222
9          bishop avram epidemic  0.022222
10                  bishop avram  0.022222
11                   news bishop  0.022222
12                avram epidemic  0.022222
13             truth news bishop  0.022222
14                  events truth  0.022222
15             events truth news  0.022222
16             news bishop avram  0.022222
17                    open sugar  0.015824
18              worse home stone  0.013333
19  become dangerous groupcorona  0.013333
20              become dangerous  0.013333

In [9]:
get_data('protest').loc[:20]

d:\desktop\github\m2-project\twittervenv\lib\site-packages\sklearn\feature_extraction\text.py:386: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['aren', 'can', 'couldn', 'didn', 'doesn', 'don', 'hadn', 'hasn', 'haven', 'isn', 'let', 'll', 'mustn', 're', 'shan', 'shouldn', 've', 'wasn', 'weren', 'won', 'wouldn'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

                           topic     score
0                 european union  0.039912
1           government decisions  0.033501
2       government decisions bad  0.033501
3       declared lebanon unknown  0.033501
4               declared lebanon  0.033501
5                  decisions bad  0.033501
6   unknown government decisions  0.033501
7             unknown government  0.033501
8     protester declared lebanon  0.033501
9                lebanon unknown  0.033501
10            protester declared  0.033501
11    lebanon unknown government  0.033501
12                   krona virus  0.033334
13           lebanese government  0.031970
14             meeting protester  0.028816
15                president aoun  0.028453
16   brazil brazilian protesters  0.024246
17              brazil brazilian  0.024246
18          brazilian protesters  0.024246
19      brazilian protesters são  0.024246
20          president paulsonaro  0.024246